# Generated by Django 3.0.5 on 2020-04-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('small_image', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='FirstCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Brand')),
            ],
            options={
                'db_table': 'firstcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('capacity', models.CharField(max_length=50)),
                ('product_image', models.URLField(max_length=1000)),
                ('like_nums', models.IntegerField()),
                ('review_nums', models.IntegerField()),
                ('mini_nums', models.IntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Brand')),
                ('firstcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.FirstCategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.IntegerField()),
                ('one', models.IntegerField()),
                ('one_half', models.IntegerField()),
                ('two', models.IntegerField()),
                ('two_half', models.IntegerField()),
                ('three', models.IntegerField()),
                ('three_half', models.IntegerField()),
                ('four', models.IntegerField()),
                ('four_half', models.IntegerField()),
                ('five', models.IntegerField()),
            ],
            options={
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
                ('score', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Score')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'userscores',
            },
        ),
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Brand')),
                ('firstcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.FirstCategory')),
            ],
            options={
                'db_table': 'secondcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='secondcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SecondCategory'),
        ),
    ]
