# Generated by Django 3.0.5 on 2020-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstcategory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='secondcategory',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='firstcategory',
            table='first_categories',
        ),
        migrations.AlterModelTable(
            name='secondcategory',
            table='second_categories',
        ),
        migrations.AlterModelTable(
            name='userscore',
            table='user_scores',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
