# Generated by Django 3.0.5 on 2020-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstcategory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='secondcategory',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
