# Generated by Django 3.0.5 on 2020-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200427_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
