# Generated by Django 3.0.5 on 2020-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200428_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
