# Generated by Django 3.0.5 on 2020-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postcomment',
            table='post_comments',
        ),
        migrations.AlterModelTable(
            name='postcommentreply',
            table='post_comment_replies',
        ),
    ]
