# Generated by Django 3.0.5 on 2020-04-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentreply',
            table='comment_replies',
        ),
        migrations.AlterModelTable(
            name='reviewcomment',
            table='review_comments',
        ),
    ]
