# Generated by Django 3.0.5 on 2020-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200429_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='is_original',
            field=models.BooleanField(null=True),
        ),
    ]
