# Generated by Django 3.0.5 on 2020-04-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'followerusers',
            },
        ),
        migrations.CreateModel(
            name='SkinProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'skinproblems',
            },
        ),
        migrations.CreateModel(
            name='SkinTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userskintone',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userskintypes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=50)),
                ('self_introduction', models.CharField(max_length=200)),
                ('profile_image', models.URLField(max_length=2000)),
                ('activity_index', models.IntegerField()),
                ('selected_agreement', models.BooleanField(default=1)),
                ('follower_username', models.ManyToManyField(through='user.FollowerUser', to='user.User')),
                ('skintone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SkinTone')),
                ('skintype', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SkinType')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSkinProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinproblem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.SkinProblem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'userskinproblems',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_skinproblem',
            field=models.ManyToManyField(through='user.UserSkinProblem', to='user.SkinProblem'),
        ),
        migrations.AddField(
            model_name='followeruser',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to='user.User'),
        ),
        migrations.AddField(
            model_name='followeruser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
