# Generated by Django 3.0.5 on 2020-05-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200427_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_index',
            field=models.IntegerField(default=0),
        ),
    ]
